### PR TITLE
Add GitHub Action to deploy docs to GitHub Pages

### PR DESCRIPTION
**Pull request by Robbert**
A designer friend wanted to check out your components, so I wanted to be able to send her a link to the hosted documentation.

### CODE REVIEW

**Comment by underdarknl** [comment]
This looks good. Thanks for taking the time to do this!
As Manon is highly configurable, we might want to build some more 'preset' css files in the future as well, each with their own set of style choices so a user could see what each module would look like with those optional choices filled out in various directions.

**Review by underdarknl — DISMISSED** [review]

**Comment by underdarknl** [comment]
@Robbert  One of your commits is not signed, could you try and sign that commit so we can merge this? Or would you like us to squash and merge and sign this? (for attribution I'd say having your commits signed and visible is more awesome obviously)

**Comment by Robbert** [comment]
✅ Verified

**Comment by Robbert** [comment]
@underdarknl Repo admin also needs to go to Settings and enable GitHub Pages, by the way, before this works. And perhaps configure that URL as homepage instead of [rdobeheer.nl](https://rdobeheer.nl/)

**Comment by dekkers** [comment]
Thanks for your contribution! I have created a slightly different github action that uses the new style upload artificate for github pages which doesn't need a gh-pages branch in the repo. Documentation can be found at https://minvws.github.io/nl-rdo-manon

**Pull request closed without merging**
