### PR TITLE
ci: clean up, use native pnpm cache, switch to ubuntu-24.04

### PR DESCRIPTION
**Pull request by ppvg**
- Clean up the workflows and setup action with consistent formatting and names for all jobs and steps.
- Revert to using `setup-node`'s [native pnpm cache](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data) (see also [pnpm docs](https://pnpm.io/continuous-integration#github-actions)).
- Switch runner image to `ubuntu-24.04`.

### CODE REVIEW

**Review by ricklambrechts — DISMISSED** [review]

**Comment by ppvg** [comment]
@minvws/irealisatie-operations: did I break everything by giving the workflow jobs human-readable names? :grimacing: 

image

**Comment by sigio** [comment]
Lijkt me niet... maar je hebt ook 1 failed workflow, (de 1e). Mogelijk dat ze wachten tot die completed/succeeded is ?

**Comment by sigio** [comment]
Ik heb de namen daar nu ook aangepast

**Comment by ppvg** [comment]
Yes, fixed. Thanks @sigio! :D

**Review by ricklambrechts — APPROVED** [review]

**Pull request merged**
